### ISSUE TITLE
In examle scene, no clicks on the buttons works

### ISSUE THREAD

**Issue by whynames** [coryleach/UnityGUI#19]
In examle scene, no clicks on the buttons works

**Comment by coryleach** [comment]
Sorry for the slow response. I've tested the buttons in 2019 however it looks like everything is still working on my end. Can you give me some more info about what's happening? 

I actually suspect maybe the demo scene was confusing as there was some transparency in the scene which may have made it appear you could click things that you actually couldn't. I will try to create an improved demo scene.

Thank you.

**Comment by coryleach** [comment]
Just pushed a slightly updated demo in 3.0.5
If the buttons continue to not work for you please let me know more details including exactly which Unity version you are using and what system you are running on. Thank you!
