### ISSUE TITLE
Please add some example or some API usage demo

### ISSUE THREAD

**Issue by takaaptech** [coryleach/UnityGUI#2]
Hi @coryleach 
I just found it, just download and try to add some script to the panel but I can not find how to use it.
Could you please add a simple example or add some API to show how to use it?
Thanks so much!

**Comment by coryleach** [comment]
Hi @takaaptech I've updated the repo to include a demo unity package you can import. It's a very simple demo as it would take me awhile to put together something that shows off everything the code does but I'll try to continue to expand the demo as I update this library.

**Comment by takaaptech** [comment]
Hi, @coryleach Thanks so much for this demo! It is awesome!
