### ISSUE TITLE
c#8 in 2019.4

### ISSUE THREAD

**Issue by BioeJD** [coryleach/UnityGUI#20]
This package seems to use the null coalescing assignment operator from c#8, but your README seems to indicate compatibility with 2019.3. For me, this doesn't compile in 2019.4.

**Comment by coryleach** [comment]
Thank you for letting me know! I will push a new version that fixes this shortly.

**Comment by coryleach** [comment]
Just published release 3.0.5 which should fix the compile issue in 2019. Let me know if there is any further problem.
